### ISSUE TITLE
Wood tools can only be created out of one type of plank?

### ISSUE THREAD

**Issue by AbduSharif** [TerraQuest-Studios/farlands_reloaded#2]
If I'm not missing something, I can't seem to be able to craft a wood pick (or any other tool) with this recipe:
![wooden_pickaxe](https://user-images.githubusercontent.com/57298920/143314416-0d89654e-8635-4fad-ad9c-45bead335211.jpg)

If you can only craft a wooden tool out of one plank then it would be nice for that to change, for example I'm in a biomie where there's only Aspen Trees in sight and so I can't craft any tool.

**Comment by wsor4035** [comment]
https://github.com/TerraQuest-Studios/farlands_reloaded/commit/7ba01fa6d3c910ba0d31a03ab83c3fb58bdbf26c fixed
