### ISSUE TITLE
Wood shovel icon is shown twice in the crafting guide

### ISSUE THREAD

**Issue by AbduSharif** [TerraQuest-Studios/farlands_reloaded#3]
For some reason the craft guide looks like this for me:
![wooden_shovel](https://user-images.githubusercontent.com/57298920/143315219-ed147298-70ab-4a18-905c-980579e95076.jpg)

**Comment by wsor4035** [comment]
https://github.com/TerraQuest-Studios/farlands_reloaded/commit/7ba01fa6d3c910ba0d31a03ab83c3fb58bdbf26c fixed
